# top level stuff you probably don't need to touch
highlighter: rouge
markdown: kramdown
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
plugins: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://ChristopherHolder.github.io/
baseurl: /
title: Chris Holder
author: Chris Holder
description: Personal blog and resume
avatar: profile2.png
email: chris.holder@mailfence.com
github: ChristopherHolder # username
twitter: cholderdev
linkedin: christopher-a-holder/
#Comment out if you don't want disqus
disqus: username
google_analytics: UA-69391421-1


# needed for travis-ci build
exclude: [vendor]
